<?php

declare(strict_types=1);

namespace Drupal\cybersource_rest\PluginForm;

use Drupal\commerce_payment\PluginForm\PaymentMethodAddForm as BasePaymentMethodAddForm;
use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Logger\LoggerChannelTrait;
use Drupal\Core\Messenger\MessengerTrait;

/**
 * Builds the Cybersource REST / Flex Microform "add payment method" form.
 *
 * Renders a polished card UI in which the PAN and CVV are Cybersource-hosted
 * Microform iframes (so card data never reaches this server); the expiry is our
 * own field. On submit the JS tokenises the card into a single-use transient
 * token and writes it to the hidden field this form posts back.
 */
class CybersourceRestForm extends BasePaymentMethodAddForm {

  use LoggerChannelTrait;
  use MessengerTrait;

  /**
   * {@inheritdoc}
   *
   * The base form only wires buildCreditCardForm() to the core "credit_card"
   * bundle; our payment method type is "cybersource_rest_credit_card", so build
   * the card form for it explicitly (mirrors the pattern other custom-bundle
   * gateways use).
   *
   * @phpstan-param array<string, mixed> $form
   * @phpstan-return array<string, mixed>
   */
  public function buildConfigurationForm(array $form, FormStateInterface $form_state): array {
    $form = parent::buildConfigurationForm($form, $form_state);
    if ($this->entity->bundle() === 'cybersource_rest_credit_card' && isset($form['payment_details'])) {
      $form['payment_details'] = $this->buildCreditCardForm($form['payment_details'], $form_state);
      // Show the customer's billing details ABOVE the card form (the base form
      // weights billing at 10, i.e. after the card); the card is the last thing
      // the customer fills in before paying.
      $form['payment_details']['#weight'] = 10;
      if (isset($form['billing_information'])) {
        $form['billing_information']['#weight'] = 0;
      }
    }
    return $form;
  }

  /**
   * {@inheritdoc}
   *
   * @phpstan-param array<string, mixed> $element
   * @phpstan-return array<string, mixed>
   */
  public function buildCreditCardForm(array $element, FormStateInterface $form_state): array {
    /** @var \Drupal\cybersource_rest\Plugin\Commerce\PaymentGateway\CybersourceRestInterface $plugin */
    $plugin = $this->plugin;

    // The capture context can only be generated by calling Cybersource; never
    // let an API/credentials failure fatal the checkout — show a safe message.
    try {
      $capture_context = $plugin->generateCaptureContext();
      $client_library = $this->clientLibrary($capture_context);
    }
    catch (\Throwable $e) {
      $this->getLogger('cybersource_rest')->error('Cannot build the Cybersource payment form: @m', ['@m' => $e->getMessage()]);
      $this->messenger()->addError($this->t('Online card payment is temporarily unavailable. Please contact us or choose another payment method.'));
      $element['cybersource_rest_unavailable'] = [
        '#markup' => '<p>' . $this->t('Online card payment is temporarily unavailable.') . '</p>',
      ];
      return $element;
    }

    $element['#attributes']['class'][] = 'cybersource-rest-form';
    $element['#attached']['library'][] = 'cybersource_rest/form';
    $element['#attached']['drupalSettings']['cybersourceRest'] = [
      'captureContext' => $capture_context,
      'clientLibrary' => $client_library['url'],
      'clientLibraryIntegrity' => $client_library['integrity'],
      'supportedCardTypes' => $this->supportedCardTypes($plugin),
    ];

    // The only value posted back to the server: the transient token (set by
    // JS).
    $element['cybersource_token'] = [
      '#type' => 'hidden',
      '#attributes' => ['class' => ['cybersource-rest-token']],
    ];

    // The polished card. PAN + CVV are mounted as Microform iframes by the JS
    // into the #cybersource-card-number / #cybersource-card-cvv slots; the
    // expiry is our own input (read client-side when tokenising).
    $element['card'] = [
      '#type' => 'inline_template',
      '#template' => <<<'TWIG'
        <div class="cybersource-rest-card"><div class="cc-card">
          <div class="cc-accepted" aria-hidden="true">
            <span class="cc-accepted-icon visa"></span>
            <span class="cc-accepted-icon mastercard"></span>
            <span class="cc-accepted-icon maestro"></span>
            <span class="cc-accepted-icon amex"></span>
          </div>
          <div class="cc-field cc-field--number">
            <label for="cybersource-card-number">{{ number_label }}</label>
            <div class="cc-input-wrap">
              <span class="cc-brand" aria-hidden="true"></span>
              <div id="cybersource-card-number" class="cc-input cc-hosted"></div>
              <span class="cc-status" aria-hidden="true"></span>
            </div>
          </div>
          <div class="cc-row">
            <div class="cc-field cc-field--expiry">
              <label for="cybersource-rest-expiry">{{ expiry_label }}</label>
              <div class="cc-input-wrap">
                <input type="text" id="cybersource-rest-expiry" class="cc-input cybersource-rest-expiry"
                  inputmode="numeric" autocomplete="cc-exp" placeholder="mm / yy" maxlength="7"
                  aria-label="{{ expiry_label }}">
                <span class="cc-status" aria-hidden="true"></span>
              </div>
            </div>
            <div class="cc-field cc-field--cvc">
              <label for="cybersource-card-cvv">{{ cvc_label }}</label>
              <div class="cc-input-wrap">
                <div id="cybersource-card-cvv" class="cc-input cc-hosted"></div>
                <span class="cc-status" aria-hidden="true"></span>
              </div>
            </div>
          </div>
          <p class="cc-error" id="cybersource-rest-error" role="alert" aria-live="polite"></p>
          <p class="cc-secure">{{ secure_note }}</p>
        </div></div>
        TWIG,
      '#context' => [
        'number_label' => $this->t('Card Number'),
        'expiry_label' => $this->t('Expiry Date'),
        'cvc_label' => $this->t('CVV'),
        'secure_note' => $this->t('Your card details are entered directly into Cybersource’s secure fields and never reach this site.'),
      ],
    ];

    // The capture context is single-use and per-request: never cache this form.
    $cacheability = new CacheableMetadata();
    $cacheability->setCacheMaxAge(0);
    $cacheability->applyTo($element);

    return $element;
  }

  /**
   * {@inheritdoc}
   *
   * @phpstan-param array<mixed, mixed> $element
   */
  protected function validateCreditCardForm(array &$element, FormStateInterface $form_state): void {
    $values = $form_state->getValue($element['#parents']);
    if (empty($values['cybersource_token'])) {
      $form_state->setError($element, $this->t('Your card could not be processed. Please re-enter your card details and try again.'));
    }
  }

  /**
   * {@inheritdoc}
   *
   * @phpstan-param array<string, mixed> $element
   */
  protected function submitCreditCardForm(array $element, FormStateInterface $form_state): void {
    // Nothing to do: the transient token (in cybersource_token) carries the
    // card metadata and is handled by the gateway's createPaymentMethod().
  }

  /**
   * Extract the Microform client-library URL + SRI hash from a capture context.
   *
   * @param string $capture_context
   *   The capture-context JWT.
   *
   * @return array{url: string, integrity: string}
   *   The client library URL and its subresource-integrity hash.
   *
   * @throws \RuntimeException
   *   If the JWT does not carry the client-library details.
   */
  protected function clientLibrary(string $capture_context): array {
    $parts = explode('.', $capture_context);
    $payload = isset($parts[1]) ? json_decode($this->base64UrlDecode($parts[1]), TRUE) : NULL;
    $data = $payload['ctx'][0]['data'] ?? NULL;
    if (!is_array($data) || empty($data['clientLibrary'])) {
      throw new \RuntimeException('Capture context is missing the Microform client library reference.');
    }
    // Fail closed: the third-party script we inject must be served over HTTPS
    // from a Cybersource host, and must carry a Subresource Integrity hash. A
    // capture context that fails either check is treated as unusable (the
    // form's caller shows the "temporarily unavailable" message) rather than
    // loading an untrusted or unverifiable script into the checkout page.
    $url = (string) $data['clientLibrary'];
    $parsed = parse_url($url);
    $host = strtolower((string) ($parsed['host'] ?? ''));
    if (($parsed['scheme'] ?? '') !== 'https' || !($host === 'cybersource.com' || str_ends_with($host, '.cybersource.com'))) {
      throw new \RuntimeException('Microform client library URL is not a trusted HTTPS Cybersource host: ' . $url);
    }
    $integrity = (string) ($data['clientLibraryIntegrity'] ?? '');
    if ($integrity === '') {
      throw new \RuntimeException('Capture context did not include a Subresource Integrity hash for the Microform client library.');
    }
    return ['url' => $url, 'integrity' => $integrity];
  }

  /**
   * The accepted Commerce credit card type ids for this gateway.
   *
   * @param \Drupal\cybersource_rest\Plugin\Commerce\PaymentGateway\CybersourceRestInterface $plugin
   *   The gateway plugin.
   *
   * @return string[]
   *   The accepted credit card type ids (e.g. visa, mastercard).
   */
  protected function supportedCardTypes($plugin): array {
    $ids = [];
    foreach ($plugin->getCreditCardTypes() as $card_type) {
      $ids[] = $card_type->getId();
    }
    return $ids;
  }

  /**
   * Decode a base64url-encoded JWT segment.
   *
   * @param string $data
   *   The base64url string.
   *
   * @return string
   *   The decoded bytes (empty string if invalid).
   */
  protected function base64UrlDecode(string $data): string {
    $remainder = strlen($data) % 4;
    if ($remainder) {
      $data .= str_repeat('=', 4 - $remainder);
    }
    return (string) base64_decode(strtr($data, '-_', '+/'), TRUE);
  }

}
